# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Ensure that Qemu and other required packages are present
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install mtools qemu-system-x86 qemu-system xorriso --fix-missing

      # Ensure we are using the same Zig version as we support
      - name: Setup Zig Compiler
        shell: bash
        run: |
          wget https://ziglang.org/download/0.14.1/zig-x86_64-linux-0.14.1.tar.xz
          tar -xvf zig-x86_64-linux-0.14.1.tar.xz
          echo "${HOME}/zig-x86_64-linux-0.14.1" >> $GITHUB_PATH

      # We want to be certain the formatting is standardised 
      - name: Check Formatting
        run: zig fmt --check kernel

      # Now we check that the OS builds
      - name: Build
        run: make

      # Assemble and run the OS in test mode using qemu
      - name: Test
        run: make run-test
